---
title: "What we do"
format: html
---
Our research examines various questions about how people learn and use language, especially in early childhood. We are interested in mental mechanisms that make it possible for people to learn, remember and use words and their meanings, rules and regularities of sentences and word forms, and mutual relations between different parts of the language system.

#### When and how children learn grammatical categories
Words belong to part-of-speech categories such as noun and verbs, sentences have subjects, predicates, objects and other elements. We are interested in how children uncover these categories, at what age they can use them to comprehend sentences, what kind of information they use to learn about them.

#### Predictive language processing and learning
When we listen to other people, we form expectations and predictions of their upcoming words. That is why we are sometimes surprised or confused when we hear something unexpected. The predictions can be helpful when we study the knowledge of grammar because they can reveal people's knowledge. But also, people sometimes learn best when they encounter unexpected outcomes, and this probably plays an important role in language learning.

#### Inflected forms of words: storage or construction?
How do people store their knowledge of inflected word forms, such as *chairs*, *mom's* or *walked*? Are these stored as separate words in their own memory "space"? Or are they created from their basic forms (*chair*, *mom*, *walk*) when needed, using linguistic rules?

#### Sentence recall: language, memory, and language impairment
In the sentence recall task, people hear sentences and their task is to immediately repeat each sentence. The task is a very sensitive measure of language skills, although it seems to be a memory task. Understanding the role of language in the task helps in developing better assessment tools, but it also addresses important fundamental questions about the structure of human memory and language system.